### ISSUE TITLE
Publishing cocoapods library

### ISSUE THREAD

**Issue by konrri** [cbaker6/CertificateSigningRequestSwift#13]
Sorry - silly question - clearly there is a problem with modulemap

In the description it says you cannot add pod
Have you tried simple command? :

pod trunk push --allow-warnings

**Comment by konrri** [comment]
did it worked?  https://cocoapods.org/pods/iOSCSRSwift

**Comment by cbaker6** [comment]
Cocoapods has been fixed

**Comment by cbaker6** [comment]
@konrri can you relinquish ownership of this pod on Cocoapods.org? I’m trying to push the pod, but I currently cannot because you have ownership
