### ISSUE TITLE
Not really an issue, it's an improvement suggestion

### ISSUE THREAD

**Issue by stklieme** [cbaker6/CertificateSigningRequestSwift#8]
If you pass the options `[.lineLength64Characters, .endLineWithLineFeed]` to the base64 encoding method you can omit the cumbersome logic in `buildCSRAndReturnString` to insert the newline characters.

    public func buildAndEncodeDataAsString(_ publicKeyBits:Data, privateKey: SecKey)-> String? {
        
        guard let buildData = self.build(publicKeyBits, privateKey: privateKey) else{
            return nil
        }
        
        return buildData.base64EncodedString(options: [.lineLength64Characters, .endLineWithLineFeed]).addingPercentEncoding(withAllowedCharacters: CharacterSet.urlQueryAllowed)
        
    }
    
    public func buildCSRAndReturnString(_ publicKeyBits:Data, privateKey: SecKey)-> String? {
        
        guard let csrString = self.buildAndEncodeDataAsString(publicKeyBits, privateKey: privateKey) else{
            return nil
        }
        
        let head = "-----BEGIN CERTIFICATE REQUEST-----\n"
        let foot = "-----END CERTIFICATE REQUEST-----\n"
        return head+csrString+foot
    }

**Comment by cbaker6** [comment]
@stklieme I tried this and it doesn't work. It does somethings incorrectly when encoding the string, creating an incorrect CSR. If you use your proposed code in place of the original code and test the CSR using https://redkestrel.co.uk/products/decoder/, it will say it can't be decoded
