### ISSUE TITLE
CSR Subject enhancement

### ISSUE THREAD

**Issue by mbonness** [cbaker6/CertificateSigningRequestSwift#9]
Please add support for the following ASN.1 types:

Locality (L)
State (ST)

**Comment by wuf810** [comment]
You could add these yourself quite easily. 

1. Add two new properties for these OIDS
2. Add two more properties for their byte arrays
3. Update the various init methods to take these new parameters and set the properties
4. Add an appendSubjectItem block for each in the buldCertificationRequestInfo() function.

This link provides details of the available OIDs : http://www.alvestrand.no/objectid/2.5.4.html 

So you'll see that :
 
Locality = 2.5.4.7 
State = 2.5.4.8

To get the values for the byte array you can use an online convertor such as : https://misc.daniel-marschall.de/asn.1/oid-converter/online.php

If you enter 2.5.4.7 you'll get back : 06 03 55 04 07

So the byte array property for this would be:

private let OBJECT_localtity:[UInt8] = [0x06, 0x03, 0x55, 0x04, 0x07]

Hope this helps. M

**Comment by wuf810** [comment]
You could add these yourself quite easily. 

1. Add two new properties for these OIDS
2. Add two more properties for their byte arrays
3. Update the various init methods to take these new parameters and set the properties
4. Add an appendSubjectItem block for each in the buldCertificationRequestInfo() function.

This link provides details of the available OIDs : http://www.alvestrand.no/objectid/2.5.4.html 

So you'll see that :
 
Locality = 2.5.4.7 
State = 2.5.4.8

To get the values for the byte array you can use an online convertor such as : https://misc.daniel-marschall.de/asn.1/oid-converter/online.php

If you enter 2.5.4.7 you'll get back : 06 03 55 04 07

So the byte array property for this would be:

private let OBJECT_localtity:[UInt8] = [0x06, 0x03, 0x55, 0x04, 0x07]

Hope this helps. M
